### ISSUE TITLE
Polar H10 upcoming support ?

### ISSUE THREAD

**Issue by Ghalr** [jlennox/HeartRate#1]
Hello.

Polar will release a new chest strap, the H10
https://www.polar.com/blog/whats-new-polar-h10-gopro-connectivity/

H7 is really great, but that one should be improved.
Will you support Polar H10 ?

Thanks.

**Comment by jlennox** [comment]
I could not definitively tell but it's advertises as being compatible with most software and supporting Bluetooth Low Energy, which leads me to believe it will work.

I'm going to close this issue, but if you (or anyone) finds that it does not work, please comment and I will re-open this issue.

**Comment by jlennox** [comment]
Also, thank you for your interest in the software. I've made a binary 1.1 release today which fixes some issues.
