### ISSUE TITLE
not issue, but features proposal

### ISSUE THREAD

**Issue by R-power** [jlennox/HeartRate#10]
dear jlennox
qhat a good job
i am polar OH1
works very good

i have questions:
1. how to manage range of values for colors?
2. could be possible to add also labels or graphics or other features for streaming woth obs and gaming?
3. max hrm and avg hrm and time count ?

thx a lot for job

**Comment by jlennox** [comment]
Thanks for the positive feedback!

> 1. how to manage range of values for colors?

Are you looking for additional functionality or are you asking for how to use `WarnLevel` and `UIWarnColor`?

> 2. could be possible to add also labels or graphics or other features for streaming woth obs and gaming?

I believe you can make the background transparent by setting the first values to `FF`, like: `FFFFFFFF`. My idea was that people could use that to display whatever they want behind it. But keep in mind, I am not a streamer so I'm not sure what the best approach would be.

It shouldn't be difficult to add a setting that lets a background be added.

> 3. max hrm and avg hrm and time count ?

What is your idea on how this is shown in the UI? What does the timecount represent? Should average be locked to a specific timecount? Like, "average of past N seconds"?

Once again, thanks for the feedback. I'm not super sure when I'll be able to get around to this. My day job is in software and lately my desire to program on the weekends has been low, but I do appreciate the feedback and I'm glad it's working well for you so far!

**Comment by jlennox** [comment]
@R-power I added background image support last night. Mind being a beta tester? :)

[heartrate_1.5-beta1.zip](https://github.com/jlennox/HeartRate/files/4772494/heartrate_1.5-beta1.zip)

**Comment by jlennox** [comment]
I've released 1.5 final. You can find it in the Release section. It has some improvements over the one attached in this case.
