### ISSUE TITLE
Feature proposal: HRV rates

### ISSUE THREAD

**Issue by Balint197** [jlennox/HeartRate#13]
Hi! 

Would it be possible to use this app for HRV measurements with compatible devices, like the Polar H10? Even just RR values would be very useful for me if possible. 

There are a couple solutions for this, but they are all built for mobile or arduino, there is no PC version. (example: https://github.com/oerjanti/BLE-Heart-rate-variability-demo) 

I need this for a realtime application, so the other features (mostly live logging) is very handy for me already with this app. Maybe I could implement it too, I'm just not sure if it is even possible.

**Comment by jlennox** [comment]
It shouldn't be too bad.

https://github.com/oerjanti/BLE-Heart-rate-variability-demo/blob/master/src/com/sample/hrv/sensor/BleHeartRateSensor.java#L193

It would need the functional equiv of that code placed around here:
https://github.com/jlennox/HeartRate/blob/master/HeartRate/HeartRateService.cs#L188

I'm not promising I'll work on this as I've got a lot of work/projects going on, but I might. Feel free to take a stab at it if you want :)

**Comment by Balint197** [comment]
Tried to work with it, but got some weird build errors I couldn't fix even with googling:
![image](https://user-images.githubusercontent.com/49960019/91737009-cdee3a00-ebae-11ea-9042-50b28b2da437.png)

Do you know what I might be doing wrong? Tried most "fixes" I found...

**Comment by jlennox** [comment]
I believe you're missing the Windows SDK. I have "Windows 10 SDK (10.0.18362.0)" selected inside the Visual Studio Installer. Perhaps it's Windows Universal CRT SDK?

This application, even though it's not a Windows Modern UI (or w/e they're called?) application, still references it because the bluetooth support inside of it is very good.

**Comment by Balint197** [comment]
![image](https://user-images.githubusercontent.com/49960019/91759759-7feb2d80-ebd2-11ea-8004-70d3be426ec3.png)

Same thing, even tried it on 3 different PCs (including adding the NuGet package from the link you gave me)... :(

And its really weird, because trying [this](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothLE) works, and its the same code there.  

But at this point, I'm not even sure if its possible to get RR values in real-time from the device, as I tried to see what data I get with the app mentioned above, and there doesn't seem to be any. Most likely the only way is to write an app with the SDK and transmit it over a connection. 

Anyway, thanks for looking into this. And please tell me if you happen to find anything later :D

**Comment by jlennox** [comment]
It's also possible it's this? https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/

I wish I wrote down the directions when I originally did this 4 years ago.

**Comment by Balint197** [comment]
Thanks, but same thing :(

I found this: https://github.com/adadurov/heartratele which is very similair, as it also uses the same windows 10 sdk. It has similair errors: 
![image](https://user-images.githubusercontent.com/49960019/91775013-635aef80-ebea-11ea-8f70-f9af8613001f.png)


While for yours, only the Windows and platform references are an error: 
![image](https://user-images.githubusercontent.com/49960019/91775096-8a192600-ebea-11ea-894b-76d4eba1d681.png)

I tried setting their "copy local" property to true as seen in a possible solution, but it sets it back immediately as the files they are looking for,  aren't present on my disk probably. 

I  really hate these "stuck" moments in programming... :D

Also, I found in the Bluetooth specifications, that if the device has RR, it should report it, and it should be easy to get it, so I'm even more angry cause it should be easy: https://www.bluetooth.com/specifications/gatt/ - see "Heart Rate Service", 3.1.1.1.4 if interested.

**Comment by jlennox** [comment]
Here's a test .exe that writes the energy use and rr-interval to the csv file. Is that good enough for you to test if it works?

I don't have time atm, but tomorrow I can write some tests that verify the bits in vs the bits out are what are expected.

[rrinterval-test.zip](https://github.com/jlennox/HeartRate/files/5153426/rrinterval-test.zip)

You can see the code here: https://github.com/jlennox/HeartRate/tree/feature/add-rrinterval

**Comment by Balint197** [comment]
Thanks for taking the time <3 Here is the  resulting file (in txt because github doesn't do csv, but its the same raw file):  

[heartrateTXT.txt](https://github.com/jlennox/HeartRate/files/5155118/heartrateTXT.txt)

But: success! I've managed to get it working: I've tried modifying the HeartRate.csproj file like you did with %programfiles(x86)%, but no luck. Then I found this: https://stackoverflow.com/questions/42157554/nodert-could-not-find-assembly/54591996#54591996 - By right clicking references, and pressing "add reference", then manually pointing to these 2 files, I managed to get it working. Really weird how it doesn't recognize these automatically. 

So I'll look into it today.

**Comment by Balint197** [comment]
So I looked into it, and tried to figure out the multiple RR measurements, like here:

[RR.txt](https://github.com/jlennox/HeartRate/files/5157441/RR.txt)

Trying to guess if it is multiple received RR signals? Or do we have to add them together to get a longer one?

What about this? Does it mean that its a longer RR as it was not registered in the 2nd row?

44075,623440625,65,NotSupported,,111,4
44075,6234518287,65,NotSupported,,
44075,6234629167,64,NotSupported,,96,4

What is the last number? (3 or 2 when multiple RR values, and 2, 3 or 4 when single values)

How do I get millisecond values from this? Not much info from https://github.com/polarofficial/polar-ble-sdk/blob/0c279df60cdef779337551b30ace1ff8c3f14090/sources/Android/android-communications/src/main/java/polar/com/sdk/api/model/PolarHrData.java#L51

I measured my RR with an app (EliteHRV) and exported it, and a part looks like:


977
1021
1172
1229
1198
1200
1152
979
906
928
1383
1266
1214

So some values are well over a second, the reporting frequency. 

I'm not sure how the bytes should be interpreted also...

Sorry for bugging you with this, you already helped a ton. I'm just not very good at these bit operations, and not sure if I understand the code completely even though I tried (and keep trying).

**Comment by jlennox** [comment]
[rrinterval-test2.zip](https://github.com/jlennox/HeartRate/files/5163288/rrinterval-test2.zip)

I think I've fixed it. The spec isn't very clear! I assumed they were bytes but what you're showing me clearly indicates they're not.

I wish this spec had example byte streams and their corresponding expectations, but I believe I have it right now.

**Comment by Balint197** [comment]
This version doesn't work for me, its stuck at the "start" label in the window. The error in debug mode:

![image](https://user-images.githubusercontent.com/49960019/92009776-4be64880-ed49-11ea-8ed3-1e332601c14b.png)

What I found meanwhile was that the bytes are good, lets say we get "210,4" for RR -> then we have to switch them because it uses LSO to MSO ordering ->and then get the new ushort from this like: 4,210 (int, 2*bytes) => 00000100 11010010 (binary, but 16 so ushort) => 1234 (int) -> and this * 1/1024 is the time in seconds, that is the difference between the last 2 R-waves that we need. I'm sorry if you did this exact thing, I didn't have time to look over your recent changes right now.  

I quickly found out something was weird with the 2 values I got in the 1st version, so I tried the UInt16 version like in other examples, which gave too large numbers. 

I don't really understand the way you get data, so I got as far as switching them, but couldn't proceed in putting them after each other and interpreting as ushort.  

See: https://stackoverflow.com/questions/52882552/getting-heart-rate-variability-from-polar-h10-uwp and https://stackoverflow.com/questions/52970763/trying-to-get-heart-rate-variability-from-polar-h10-bluetooth-low-energy-sample - they talk about a specification that is no longer available, that had this info...

And yeah, the dynamic filename was also an issue for me, but its not a big deal so I forgot to report it :D

Thanks for your help again.

**Comment by jlennox** [comment]
Ah sorry, I don't have my monitor on me atm so I can't test this code for real. I don't know much about the winrt api's but they're in general very strange and I didn't expect ReadBytes to work like that. I think this fixes it? 
[rrinterval-test3.zip](https://github.com/jlennox/HeartRate/files/5163681/rrinterval-test3.zip)

**Comment by Balint197** [comment]
Thanks, this works great!

> Also, would it be expected that the default output would be in seconds and not the *1024 format?

I think for the log file its fine like this, because it shows the "raw" data of the sensor, while the "real" value in milliseconds will have some rounding (eg.: 828 sensor becomes 808,5938 milliseconds). I would guess some users would rather work with the raw data because of this. 

But the reason why many users would want RR data is for HRV calculation, and for that they need a file called IBI - inter-beat-intervals. Its basically the RR values _in milliseconds_ without decimals, each reading under the one before. Theres sites and programs to analyze these files and get data out of it. (for example  https://www.kubios.com/ , but there are also many repos here on github as well) 
[IBI file example.txt](https://github.com/jlennox/HeartRate/files/5164345/2020-08-30.13-59-57.txt)

So I would make an option in the config file to also generate an IBI file like this if the RR rates are available. (btw I haven't seen other repos do this, so yours would be the first)


But its your program so it's your call, this is just what I would personally do. :) I will do HRV calculation in real time with another program most likely, but I might try to implement it here as it could be faster. If you are still interested in your original motivation for this program, you might want to do this as well, as it also monitors stress levels similair to bpm, but its an even better indicator!

> Here's that XML from that dead link:

Yea that would have made things easier :D 

And sorry for not being able to contribute more. The early technical problems were really annoying and the code was a bit over my head in some places. Still, I learned a lot. Thanks for everything. :)

**Comment by jlennox** [comment]
Can you write out the formula to compute HRV? That plus the option to generate IBI files shouldn't be too tricky.

**Comment by Balint197** [comment]
Unfortunately HRV is not that easy, it has multiple properties: https://en.wikipedia.org/wiki/Heart_rate_variability#Analysis - but luckily you don't need all that.

The most common applications use exclusively RMMSD from this. A less common one is SDNN. Both of these are easy to calculate. [(short explanation - see from "Time-domain methods" title)](https://imotions.com/blog/heart-rate-variability)

This consumer application applies a score to RMMSD by using natural logarithm: https://help.elitehrv.com/article/54-how-do-you-calculate-the-hrv-score - makes the results easier to understand.

For this programs original use, I would do these calculations for the last 5 minutes at least, maybe once a minute or half minute (though you can obviously make it easily adjustable). 

Or if you want something even more in-depth, you can use the many existing projects for this stuff, like:  https://pypi.org/project/hrv-analysis/ - you can draw cool looking plots to the UI with this pretty easily. 

And IBI is even easier of course :)

**Comment by Balint197** [comment]
> That's a bit much for me now but maybe this weekend. 

The data we got with the RR readings is fine for me already, so don't need to hurry because of that :D

Found a couple bugs, but it doesn't crash, and no error messages in VS:

- I didn't modify the path for the logfile, and used the same format for the IBI file, but it didn't place it in that directory, rather in the same directory as the EXE, with the given path as filename: (used "C:\Users\hajna\HeartRateLogs\heartrate.csv" as destination)
![image](https://user-images.githubusercontent.com/49960019/92139417-fe80de80-ee0f-11ea-951f-d07abb6a7841.png)

- datetime formatting is broken still, the 2nd file in the screenshot is with %date% only, I don't know how I got the 3rd from top version, can't replicate it. It was the second recording though...

- IBI file is basically just ones: 
[C--Users-hajna-HeartRateLogs-IBI01-01-0001.txt](https://github.com/jlennox/HeartRate/files/5169855/C--Users-hajna-HeartRateLogs-IBI01-01-0001.txt)

**Comment by jlennox** [comment]
Can you show me the corresponding csv file to that C--Users-hajna-HeartRateLogs-IBI01-01-0001.txt? I'm not sure why it's all 1's, the other bugs were easy tho.

**Comment by Balint197** [comment]
[C--Users-hajna-HeartRateLogs-IBI0001-01-01 12-00 de..txt](https://github.com/jlennox/HeartRate/files/5170007/C--Users-hajna-HeartRateLogs-IBI0001-01-01.12-00.de.txt)

[C--Users-hajna-HeartRateLogs-heartrate0001-01-01 12-00 de..csv.txt](https://github.com/jlennox/HeartRate/files/5170014/C--Users-hajna-HeartRateLogs-heartrate0001-01-01.12-00.de.csv.txt)

IBI and its corresponding CSV (as txt) I just created. It does this for every file. 

What you are probably doing wrong is that you need: RR / 1024 * 1000, as RR from the sensor is 1/1024th of a second, and we need millisecond, 1/1000th

**Comment by jlennox** [comment]
Ah right, I was giving seconds. Should fix all those issues: 
[rrinterval-test5.zip](https://github.com/jlennox/HeartRate/files/5170064/rrinterval-test5.zip)

**Comment by Balint197** [comment]
Yup, everything works great, thanks!

**Comment by Balint197** [comment]
Hi! 

Sorry for bugging you again with this, its just a tiny request.

As I am trying to read the logfile with another program in real time, I had the other program crash when there were read-write conflicts. My program doesn't have a way to check if a file is being open elsewhere, it just crashes. To check if your program is working with the files, I implemented a very simple way to indicate it: before saving, create a file, and after delete it - this way I can check if its ok to open it. 

Basically in FileWriters.cs I modified from line 69: 

```
            if (data != null)
            {
                using (File.Create(@"c:\users\hajna\HeartRateLogs\Reading.file")) { }

                File.AppendAllText(_filename, data);

                File.Delete(@"c:\users\hajna\HeartRateLogs\Reading.file");
            }
```

Just 2 new lines. It works, but when I try to build the app, I get tons of build errors sometimes. I somehow got to build it once, but then in some weird way the filenames you corrected got messed up again (and im on the latest git branch...).

I didn't make a more sophisticated version because I don't think most people will need this, so didn't make a pull request. Could you please build this for me and send it? Thanks a lot!

**Comment by jlennox** [comment]
This should fix your issue:
[rrinterval-test6.zip](https://github.com/jlennox/HeartRate/files/5288826/rrinterval-test6.zip)

I made it so it opens the file with appropriate read/write share flags: https://github.com/jlennox/HeartRate/commit/2c5946aacd2801038fa7fe909fb862a8f68426a4

Let me know if it works!

**Comment by Balint197** [comment]
Thanks a lot!

The logfile is fine, but the IBI file has every line like this instead of a reading:

```
System.Linq.Enumerable+WhereSelectArrayIterator`2[System.Int32,System.String]
```

I couldn't test my program with it yet, but I'll make sure to do so soon. Thanks :)

**Comment by jlennox** [comment]
Woops. I forgot to run my own tests :)

[rrinterval-test7.zip](https://github.com/jlennox/HeartRate/files/5293155/rrinterval-test7.zip)

**Comment by Balint197** [comment]
Thanks, this works again 👍

My problem is that the program I'm using to read the files ([Godot game engine](https://github.com/godotengine/godot)) doesn't seem to have the ability to detect if a file is open elsewhere, only by itself (my use case is not really traditional for a game engine :) ). This means it simply freezes when there is a conflict, and doesn't throw errors :/

So with this new version it just instantly freezes and doesn't even work most of the time when it did so previously. I'll implement the awful code i wrote above, it should work. My program can detect other files obviously, so this version should work. 

Thanks!

**Comment by jlennox** [comment]
Ahh, I see. Let me make a small change to the code for you, otherwise it wont work because now it keeps the file open. https://github.com/jlennox/HeartRate/pull/15/commits/2febe96341e7d36a1dbad61ffcdb71cbbee81653

If you can open the files in Godot game engine with the proper share flags, you should be ok without this.

**Comment by jlennox** [comment]
Also, I think this https://github.com/jlennox/HeartRate/pull/15/commits/01acd887a5c51f69755c92dc7c09d9cc616948fb should make it easier for you to build.

**Comment by Balint197** [comment]
Thanks, it works now!

It was my fault. The [open method](https://docs.godotengine.org/en/stable/classes/class_file.html) returns an error, but I thought it would be already too late as it freezed and there were no errors in the editor. After checking for it, it lets me proceed and no freeze. 

It has worked for like 10 minutes now, and I print when theres an error so there are about 8 file open errors that were thrown in this time. 

Thanks for your support :)
