### ISSUE TITLE
Sending keystrokes?

### ISSUE THREAD

**Issue by DieKatzchen** [jlennox/HeartRate#16]
This may be a very niche use, but would it be possible to have the program send keystrokes at the same rate as the heartbeat? That way I could assign that key to a heart beating animation on an avatar and make it beat like my real heart. Like I said, very niche.

**Comment by jlennox** [comment]
Would it send the keystroke to a specific window? If so, how would that window be identified (would by title work?)

**Comment by DieKatzchen** [comment]
Could probably get away with just the active window, or the title. There should only be the one VRChat window active at any time.

**Comment by jlennox** [comment]
@DieKatzchen Hey sorry, this slipped away from me. Are you still interested?

**Comment by jlennox** [comment]
I'm closing this out, but if you're still interested reply here and I'll reopen.

**Comment by DieKatzchen** [comment]
Whoops, it slipped away from me too. Yes I'm still interested.
