### ISSUE TITLE
Feature Request - Text Alignment

### ISSUE THREAD

**Issue by Dkasakaitis** [jlennox/HeartRate#17]
Hi,

Would it be possible to add a text align feature to the software? For easy realignment of numbers in the window. For left/right/center alignment?

**Comment by jlennox** [comment]
@Dkasakaitis 
[textalign-test.zip](https://github.com/jlennox/HeartRate/files/5575756/textalign-test.zip)

Mind testing?

Inside the context menu that shows when you right click the window or taskbar icon, there's a menu to select from in there.

**Comment by Dkasakaitis** [comment]
Thanks for the quick reply.

Got this error when launching the program.

![image](https://user-images.githubusercontent.com/23727748/99846946-2c540480-2b6f-11eb-8519-8acbebaed776.png)

************** Exception Text **************
System.ComponentModel.InvalidEnumArgumentException: The value of argument 'value' (0) is invalid for Enum type 'ContentAlignment'.
Parameter name: value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at HeartRate.HeartRateForm.UpdateUI() in C:\Users\joe\Dropbox\_code\HeartRate\HeartRate\HeartRateForm.cs:line 251
   at HeartRate.HeartRateForm.HeartRateForm_Load(Object sender, EventArgs e) in C:\Users\joe\Dropbox\_code\HeartRate\HeartRate\HeartRateForm.cs:line 120
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jlennox** [comment]
Ah I missed one. Mind testing again? 
[Uploading textalign-test2.zip…]()

**Comment by Dkasakaitis** [comment]
Download link not working.

Also is there a possibility of consistently writing out the current reading to a .txt file?

**Comment by jlennox** [comment]
Fixed link I assume: 
[textalign-test2.zip](https://github.com/jlennox/HeartRate/files/5576316/textalign-test2.zip)

There's `LogFile` and `IBIFile` https://github.com/jlennox/HeartRate#settings

It's not exposed through the context menus but it is inside the XML settings.

**Comment by Dkasakaitis** [comment]
Alright, all working nicely. Thanks for the update.

**Comment by Dkasakaitis** [comment]
I find that some fonts tend to clip to the bottom with any setting in the program.

Also font-styles are not implemented?

**Comment by jlennox** [comment]
> Also font-styles are not implemented?

[textalign-test3.zip](https://github.com/jlennox/HeartRate/files/5578112/textalign-test3.zip)

The select UI font dialog now supports the font styles portion (italic, bold, etc).

> I find that some fonts tend to clip to the bottom with any setting in the program.

Ya... font metrics are a horrible and confusing topic. I've added a reduction factor of .8 to the font size, but that's really not ideal :/

Let me know if that helps at all. There seems to be a large top margin that I'm not sure where it comes from. Let me see what I can figure out, but in the mean time, let me know how the font styles work for you.

**Comment by jlennox** [comment]
> There is no special padding... all fonts have some whitespace around the characters and this font has more than others; the larger the font, the more whitespace.  The only thing you can do is to draw the text at a location outside the visible bounds of the control so that the actual characters begin closer to the upper left corner.

That seems to be the closest I've seen to a correct answer about what we're seeing. I've even moved over to custom text rendering instead of using a control, but still no dice.

I think this might be doing a lot better though? I think you'll never see it clip. It _might_ have a crashing issue though?

[textlaign-test4.zip](https://github.com/jlennox/HeartRate/files/5578180/textlaign-test4.zip)

**Comment by Dkasakaitis** [comment]
Yes, this is way cleaner now. Clipping seems to be resolved. No crashing yet.

Thank you for all the quick updates.

**Comment by Dkasakaitis** [comment]
> Yes, this is way cleaner now. Clipping seems to be resolved. No crashing yet.

Never mind seems a few minutes into use the program freezes and stops responding.

**Comment by jlennox** [comment]
@Dkasakaitis Let me know if this one fixes the crashes: 
[textalign-test5.zip](https://github.com/jlennox/HeartRate/files/5585078/textalign-test5.zip)

**Comment by Dkasakaitis** [comment]
The program still freezes/crashes a few seconds or minutes into use,.

**Comment by jlennox** [comment]
Ahh, it took me a bit to reproduce but we were seeing two different issues :) The original crash I was worried about is fixed.

I'm writing this down now because I can't work on it immediately: `Service_HeartRateUpdatedCore` calls `Invoke()` while holding lock on `_updateSync` but Invoke is blocked because the last paint hasn't completed.

**Comment by jlennox** [comment]
@Dkasakaitis it should be fixed now. 
[textalign-test6.zip](https://github.com/jlennox/HeartRate/files/5593191/textalign-test6.zip)

**Comment by Dkasakaitis** [comment]
Alright tested for about a hour and no freezes/crashes so far.

While testing though, I was wondering if it would be possible to add a opacity feature to the background of the program?

Also keeping the window size static and using the font size instead?

**Comment by jlennox** [comment]
> would be possible to add a opacity feature to the background of the program?

This gets a bit tricky. The problem here is it's not just the visibility that it controls, but the interaction. So when I do this, it becomes impossible to move the window around and stuff. There's probably someway to fix it but I'm not sure.

I believe last time someone requested this, the compromise was to add in background image support?

> Also keeping the window size static and using the font size instead?

I've added in a toggle that lets you select "Do not scale font" and then the font size selection inside the font selection dialog will be used. The sizing is in pixels, not pt btw.
[textalign-test7.zip](https://github.com/jlennox/HeartRate/files/5604478/textalign-test7.zip)

**Comment by Dkasakaitis** [comment]
Been using for the last few hours and the release seems stable.

> This gets a bit tricky. The problem here is it's not just the visibility that it controls, but the interaction. So when I do this, it becomes impossible to move the window around and stuff. There's probably someway to fix it but I'm not sure.

This doesn't matter as much, as I can work around this with a luma key.

Thank you for adding the static font feature. Is there any way of permanent locking the window size too?

**Comment by jlennox** [comment]
It should now save the window size between sessions, and you can set it to an explicit pixel dimension inside the .xml

[textalign-test8.zip](https://github.com/jlennox/HeartRate/files/5609327/textalign-test8.zip)

Let me know if that does what you're looking for.

**Comment by Dkasakaitis** [comment]
> It should now save the window size between sessions, and you can set it to an explicit pixel dimension inside the .xml

Thank you that's exactly what I am looking for.

Also thanks again for all the updates.
