### ISSUE TITLE
Apple Watch + Heartcast: Worked once, never again

### ISSUE THREAD

**Issue by philipsd6** [jlennox/HeartRate#34]
There is an iOS app [HeartCast](https://www.heartcast.app/) that exposes the heart rate from a linked Apple Watch via BLE. I set it up and paired it with my Windows 10 laptop, started `heartrate.exe` and... it worked! 

However, I made some config changes, restarted it and it didn't work. Since then, I've added the registry info as described in the readme, removed `%APPDATA%\HeartRate`, unpaired, re-paired, restarted my laptop, removed the registry info... and while I have no problems pairing, and it initially shows in my bluetooth device as connected, `heartrate.exe` cannot find it:

Paired and connected:
![ApplicationFrameHost_sGay4ifjnK](https://user-images.githubusercontent.com/908201/162224544-faf6f047-b0d5-4fa6-b6a3-b62edee505ad.png)

```
4/7/2022 10:00:57 AM: HeartRateService: Unable to locate a device.
4/7/2022 10:00:57 AM: HeartRateService: InitiateDefault exception: System.ArgumentNullException: Unable to locate heart rate device. Ensure it's connected and paired.
Parameter name: device
   at HeartRate.HeartRateService.InitiateDefaultCore() in C:\Users\joe\Dropbox\_code\HeartRate\src\HeartRate\HeartRateService.cs:line 103
   at HeartRate.HeartRateService.InitiateDefault() in C:\Users\joe\Dropbox\_code\HeartRate\src\HeartRate\HeartRateService.cs:line 71
```

How can I determine what went wrong? If I hadn't had it initially working fine I would assume it just doesn't work, but... it *was* working!

After some time, the Bluetooth device (as in the picture above) turns to just "Paired" not "Connected", and has the same results in the app logs.

**Comment by jlennox** [comment]
@philipsd6 Sorry for the delayed response.

Tbh, I'm not really sure. I find diagnosing issues with bluetooth to be unfortunately very complex. A lot of information feels withheld making it a black box.

Have you made any progress on this?

**Comment by philipsd6** [comment]
no, and I've kind of given up on it -- I find my experience much the same -- very complex dealing with bluetooth, and without decent logging/error messages just impossible to troubleshoot
