### ISSUE TITLE
Feature request: UDP Logging

### ISSUE THREAD

**Issue by Gummientchen** [jlennox/HeartRate#35]
Hi,

I was wondering if it would be possible to integrate an UDP logging functionality so measurements could be sent to other programs easier. It would need a configurable IP address and port to which the data gets sent to.

I'm sadly not proficient enough in C# to implement this myself, but I could help with testing the functionality.

**Comment by jlennox** [comment]
Should be easy enough. You're thinking it goes outbound and doesn't listen for connections?

What do you imagine the packet looks like?

I imagine it's intended for localhost only so udp unreliability isn't a factor?

**Comment by Gummientchen** [comment]
Yes, it would be outbound only. Package could be the same as the output of the CSV logger => 03.05.2022 18:38:25,88,NotSupported,,"661"

Reliability of every packet arriving isn't a problem for my intended usage, as it shows the data live.

**Comment by jlennox** [comment]
This worked for me locally testing with `netcat -ulp 2115` as a listener. The setting looks like `<UDP>127.0.0.1:2115</UDP>`

Must use 127.0.0.1, localhost wont work. Output is \n delineated.

Mind giving it a test and providing feedback?

[heartrate-udp-test1.zip](https://github.com/jlennox/HeartRate/files/8612524/heartrate-udp-test1.zip)

**Comment by Gummientchen** [comment]
That was amazingly fast. Thank you very much. It works like I expected it to work.
