### ISSUE TITLE
New device Compatibility

### ISSUE THREAD

**Issue by Simpleguyxorpad** [jlennox/HeartRate#47]
Sorry to open this as an issue, but I have a smart band of a not very well known brand, I get it to connect to windows but your program does not recognize it, do you think it would be possible to add compatibility with my smart band? If I can add something to help you let me know, and sorry for the inconvenience.

**Comment by jlennox** [comment]
What brand/model is the band?

It really comes down to "does it provide the standard BTLE Heart Rate device?"

**Comment by Simpleguyxorpad** [comment]
Thanks for your reply, but sadly  my smart band  got stolen a few days ago, so I guess we'll never know.... T_T

**Comment by SSaiSatvik** [comment]
@jlennox I am Scosche rhythm24 sensor. It has BLE. Can you help me in connecting it to Laptop. I can see the devices on my mobile but cannot find them in windows.

**Comment by jlennox** [comment]
I'm sorry that it outside the scope of what I do here. I recommend google, chatgpt, and being sure your computer has a bluetooth radio.
