### ISSUE TITLE
Device Compatibility - WHOOP 4.0 and 3.0

### ISSUE THREAD

**Issue by AlcorSalvador** [jlennox/HeartRate#49]
This is a band normally tied to a subscription service. After a long time I decided to cancel. Now the band is functionally E-waste. I imagine many people who have moved away from them for one reason or another will end up shoving it in a drawer, reselling or throwing it away. 

The error I'm getting claims that the band is being used by another program, asking to turn on and off the BT Adapter. I currently have a 4.0, but I used to have a handful of 3.0's. Worth mentioning that Windows 11 assumes the battery of the device is at 100% regardless of the actual charge. My experience with Whoop has also been full of BT problems in general, refusal to connect to certain devices and the band just forgetting it knows how to pair at times. These were mostly with the 3.0 Bands. My first 4.0 refused to connect to the app, but my second one worked just fine. 

Might be a long shot, but I think a lot of people who wish to cut the subscriptions and those who already have would be grateful.

**Comment by jlennox** [comment]
If I'm understanding correctly you're asking for.me to add support for a proprietary protocol. If someone did the reverse engineering and implementation I'd be glad to assist but doing that myself is not something I am interested in pursuing.
