### ISSUE TITLE
OBS cannot find HeartRate as a window

### ISSUE THREAD

**Issue by janbpunkt** [jlennox/HeartRate#6]
Hey there jlennox,

I'm very glad that I found your HRM, because that was exactly what I was looking for to use on my twitch stream.

Unfortunately OBS cannot locate HeartRate as a window - it simply does not show up.
Is there a way to fix it?

Since both of my screens are loaded with stuff while streaming, I cannot fall back on region capture.

Thank you so much :)

Jan

**Comment by jlennox** [comment]
Hi Jan.

I've pushed a fix and made a new release. All of the comments are in release 1.3.

If you have any issues, please reopen this issue or leave a new comment.

Thanks!
Joe
