### ISSUE TITLE
Fix a loss of connection

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [jlennox/HeartRate#7]
While it detected my hrm right from the start, it sometimes loses connection, meaning it stops updating. Which method(s) needs to be rerun in this case to reestablish connection?

**Comment by ErfolgreichCharismatisch** [comment]
Don't everybody speak up at once!

**Comment by jlennox** [comment]
Hey! Sorry, I missed this issue.

Looking at the code I can see how this would happen, I think. Unfortunately my bluetooth dongle and heart rate monitor have gone missing. Let me dig around a bit and see what I can find, if nothing, I'll order something new.

The issue, I believe, is when the device disappears that `HeartRateService.InitiateDefault` isn't re-run in anyway. There's a bit of a code overhaul required for this but nothing too scary.
