### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ardittristan** [jlennox/HeartRate#8]
It's no issue if it's too much work to do, but is it possible to add a config option that enables logging the heart rate to a json/database file so it can be used for statistics afterwards?

**Comment by jlennox** [comment]
I like the way this sounds! I've got no idea where my bluetooth dongle or heart rate monitor is, so would you be willing to beta test?

[heartrate_1.4-beta.zip](https://github.com/jlennox/HeartRate/files/2794208/heartrate_1.4-beta.zip)

There's two new settings entries:

| Setting    | Type | Default  | Description |
|------------|------|----------|-------------|
| `LogFormat` | text | csv | The format to write to the LogFile. Only "csv" is valid. |
| `LogFile` | text | "" | The full path of where to write the logged data to. If empty, no file log is kept. |

**Comment by ardittristan** [comment]
With the beta there's 2 things that's happening, or the program doesn't start at all, or it starts and instantly freezes. I don't know what decides which of the 2 happens. What I also noticed is that 1.3 creates a filled settings file if I remove the old one, but 1.4 creates an empty settings file.

**Comment by jlennox** [comment]
I'll take a look at that this weekend. This project has no test introspection into it, so I'll add that so I can work on it without needing to find my heartrate monitor and company.

Mind sharing your configuration?

Thank you for testing!

**Comment by ardittristan** [comment]
I ran the programs a few more times to get the config files, and it actually booted and worked 2 times. But the only times that happened was when I removed the settings file from AppData and let the program regenerate it, and it only worked about 30% of the time.

settings I tried to use:
https://pastebin.com/m5ty41yu (1.3 generated)
https://pastebin.com/ZwgFRRyc

settings 1.4 generates when I remove the old settings:
https://pastebin.com/E8v59HEs

**Comment by jlennox** [comment]
Can you try with the entries like this:

```
<LogFormat>csv</LogFormat>
<LogFile>D:\Downloads\MyLogFile.csv</LogFile>
```

I think that'll fix your issue.

**Comment by ardittristan** [comment]
Even if I add those lines to a full config 1.4 still freezes on startup/doesn't start unless I remove the settings.xml which makes it start but creates an empty settings.xml file

**Comment by jlennox** [comment]
Ah ok. I will investigate this over the weekend. Thank you for the feedback.

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/51801566-e1515a80-223f-11e9-8a1c-b80a98ed065a.png)
It logs and starts now for me. Only suggestion I have is maybe an option (or when in config it doesn't end with .csv but with a folder) that it automatically makes a csv file with the date and time in the name, so it doesn't write to the same log file if you use the program one day later for example and haven't moved the old log file. This is only a quality of life request tho.

**Comment by jlennox** [comment]
[heartrate-1.4-beta3.zip](https://github.com/jlennox/HeartRate/files/2800315/heartrate-1.4-beta3.zip)

I've made it so a token can be put into the filename and so the date column can have a custom formatter specified. Change the filename to look something like: `C:\users\joe\desktop\heartrate-%date%.csv`

Let me know how it goes!

Updates to the docs:

| Setting    | Type | Default  | Description |
|------------|------|----------|-------------|
| `LogFormat` | text | csv | The format to write to the LogFile. Only "csv" is valid. |
| `LogDateFormat` | text | OA | The format to write the date column as. See `Datetime formatting.` |
| `LogFile` | text | *empty* | The full path of where to write the logged data to. If empty, no file log is kept. A `%date%` token can be included to substitute in the date. A custom formatter can be included, such as `%date:MM-dd-yyyy%` Example: `C:\users\joe\desktop\heartrate-%date%.csv`  |

### Datetime formatting
Datetime formatting is done using the standard C# syntax. One special exception
is "OA" which will convert to an "OLE Automation Date" formatted date, which is
useful for Excel.

**Comment by ardittristan** [comment]
now it doesn't create/write to csv files anymore. It is doing something because I see the loading circle show up next to the mouse, just like it did at the old one (probably because it writes to a file) but nothing gets added to the file in this version/the file doesn't get created if I don't fill in an already existing file. this happens both with and without the %date% tag added to the file.

**Comment by panamantis** [comment]
I found the LogDateFormat of "s" better then "OA".  "s" is sortable:  2020-08-07T23:01:49
And OA wasn't working for me well.

**Comment by jlennox** [comment]
@panamantis I believe there's a bug in the code that stopped it from trying to the correct filepath. I believe it never actually parses the `%date%` input out of the filename. Uh oh.
