### ISSUE TITLE
Stops Updating BPM until Program restart.

### ISSUE THREAD

**Issue by dtawom** [jlennox/HeartRate#9]
After somewhere between 5 & 15 minutes the BPM stops updating in your app using my Polar OH1.  Simply exiting the program and re-starting it seems to work okay, but that's hard to do while in a twitch stream.  I've tried adjusting the timeout setting to no avail.  I also tried creating a task scheduler task to basically just close the program and re-open it every 5 minutes, but for whatever reason this doesn't seem to be working either.  
I'm not super techy when it comes to the programming side of things, I'm even having trouble with the color codes for the text and background to make it a transparent.
I will gladly compensate you for your time and any assistance you can provide solving these problems.

Background:
I have a polar OH1 armband I got for the purpose of including my heart rate in my twitch beat saber VRfitness channel.  Initially I assumed finding a PC program to display / log heart rate from a bluetooth armband would be simple, but after much research I found exactly two.  Yours which seems to work well and some silly one from the MS app store that locks up as soon as you try to put it in OBS.  I know you intend to make 0 on this app, but I'm sure there are tons of streamers out there that would be willing to pay you for it, myself included.
Addition Suggestions: 
1) Average, High, & Low BPM.
2) Calories burned (based off wieght input & bpm formula)
3) Menu based settings changes for font, color, size, & background colors.

**Comment by jlennox** [comment]
Regarding "Calories burned (based off wieght input & bpm formula)" do you have a link to the formula?

Adding a menu might be pretty easy if it's added to the task bar icon.

**Comment by dtawom** [comment]
I did try some of the color code sites before contacting you and maybe it's just my lack of understanding, but all the sites had # sign and 6 digits for the code, your default settings file had 8 digits.  I tried replacing the background color with green screen color and it never changed, maybe I'm just confused as to what the different descriptions in your settings file means.  I tinkered around with the 6 digit codes for about 1/2 hour and it seemed the only thing I could get to change color was the default number color and the warning colors.

Thanks for using your programming skills in a generous way.  I'm not a rich man, nor am I gifted in the art of code, but I can respect anyone who donates their wisdom to create something that helps others.

Yes just the stats of the session.  This is the app from the app store I was referring to that locks when tied to obs.  It displays min, max, and average heart rate for the session as well as calories burned.  But it does not ask for sex, weight, or age so I don't think it's calories estimate is very accurate.  https://www.microsoft.com/store/productId/9WZDNCRDKW2V

The calories burned equation is different for men and women.  
Formulas for Determination of Calorie Burn if VO2max is Unknown
Male: ((-55.0969 + (0.6309 x HR) + (0.1988 x W) + (0.2017 x A))/4.184) x 60 x T
Female: ((-20.4022 + (0.4472 x HR) - (0.1263 x W) + (0.074 x A))/4.184) x 60 x T
where
HR = Heart rate (in beats/minute)
W = Weight (in kilograms)
A = Age (in years)
T = Exercise duration time (in hours)
The VO2max is something most people won't have, but it talks more about it here if you're curious at all.
http://www.shapesense.com/fitness-exercise/calculators/heart-rate-based-calorie-burn-calculator.shtml

I didn't know the tray icon had a hover function, I will check that tonight and get back to you.  When it occurs nothing really happens, the monitor is just locked on the last number reading it had and just stops updating.  I've tried adjusting the timeouts and it doesn't seem to make a difference.  My task scheduler trick seems to work once I tweaked it right by just restarting the program every 5 minutes seems to keep it working.  I will set a stopwatch and get back to you with exactly how long it takes to drop out and what the hover over taskbar icon says.  If you like I can try the new 1.4 beta with some logging options and get back to you with a log as well.

**Comment by jlennox** [comment]
I may of fixed the stalling issues you were having. Mind beta testing? [heartrate-1.4-beta4.zip](https://github.com/jlennox/HeartRate/files/2819649/heartrate-1.4-beta4.zip)

I've got a new bluetooth dongle due here this weekend, but until then, I've got no decent way to test my changes.

Btw, my program showing the colors as 8 digits was a bug, woops. It should of been 6. It making the default config with 8 is fixed in this build. The 2 leading zeros were meaningless.

**Comment by dtawom** [comment]
> I may of fixed the stalling issues you were having. Mind beta testing? [heartrate-1.4-beta4.zip](https://github.com/jlennox/HeartRate/files/2819741/heartrate-1.4-beta4.zip)
> 
> I've got a new bluetooth dongle due here this weekend, but until then, I've got no decent way to test my changes.
> 
> The colors are 8 numerics because they're "ARGB." Which stands for Alpha, Red, Green, Blue. So there's 255 possible values, 00 to FF for each of those. For alpha, 00 means fully opaque, and FF means fully transparent. So say you found the color code "#112233" and wanted to use it, you'd put "00112233" in the config.

Mousing over the taskbar icon on 1.3 tells me nothing when it's hung up on a BPM number.  
I tried the 1.4-beta4 and the program wouldn't launch for me, nothing happens and it doesn't show up in task manager.  I did find after deleting the config file from app data, removing my oh1 then re-pairing it the 1.4 launched for me, but after a restart the program wouldn't launch again.  The cursor just flashes a few times then nothing in task manager.  I've also tried a few compatibility modes and running as administrator.

I'm running win 10 x64 btw.

Thanks for the info on  color codes, when I get the app working again I'll try tinkering with it.

**Comment by dtawom** [comment]
I know progress on this may have stopped, but I really need a consistently working product I can use with obs as all other options have failed me at this point.  I know you said you've got a lucrative job and don't need the money, nor do you have any use for this software, but myself and others need a consistently functional program that won't break the bank for twitch.  I'll buy you a usb bluetooth adapter, an OH1 polar armband like I have, and compensate you monetarily for your time on this project.  Just give me a list of requests and I will fulfill them to get this project complete.  Thanks again for your expertise and time.

**Comment by dtawom** [comment]
For others using this program I have found a workaround and an alternate program with a lot more options.  First the workaround:
I tried using task scheduler to kill the program and reopen it every five minutes or so, but that didn't work so I decided instead to do a macro.  I used macro recorder and just made a small executable of it.  If you just want the executable you can get it from my google drive here: https://drive.google.com/file/d/1Vp0EXPO85MeNhsSvFCdl0eqMHRD6Y9Ga/view?usp=sharing
For the executable to work you will need to put the 1.3 version of this program in this path: D:\HeartrateMonitor\HeartRate.exe
This macro will simply wait 5 minutes, then close the Heartrate.exe window, then open it again, rinse repeat.
If you want to modify the macro yourself to have the program in a different location here's all it is:
LABEL : START
DELAY : 300000
CLOSE WINDOW : Heart rate monitor : 0
WAIT FOR : Heart rate monitor : disappear : 5000 : 0
DELAY : 2000
OPEN FILE : D:\HeartrateMonitor\HeartRate.exe :  : 0
GOTO : START

Now for the alternate:
Golden Cheetah is the name of the program you can download it from here: 
https://www.goldencheetah.org/ 
I didn't find this initially when looking for a monitoring program because it's advertised as a cycling tracking history program, but it has a Train tab that tracks live heart rates from all sorts of sensors and has a lot of additional heart rate data.
The only drawback to this program is that right now it has an issue with initially adding your bluetooth heart rate monitors.  In order to add a bluetooth adapter you have to have an Ant + usb receiver attached to the computer.  After your bluetooth heart rate monitor is added to Golden Cheetah you can simply remove the Ant + usb receiver and the bluetooth heart rate monitor will continue to work indefinitely.  So you'll have to spend $15 on one of the generic dongles off Amazon to get this working if your heart monitor is bluetooth.  From what I've read it works well and many other streamers are using it.  This is the one another Golden Cheetah user has purchased and verified functionality with:
https://www.amazon.com/gp/product/B01M3VQP6Z/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
If you want to read more about the bluetooth issue with Golden Cheetah you can read about it here:  https://github.com/GoldenCheetah/GoldenCheetah/issues/2771

**Comment by jlennox** [comment]
Sorry, I've been having issues where the program to add a bluetooth device in Windows crashes, so I need to invest the time into making a mock device source that mimics your issues. I contacted Microsoft with the output from a debugger attached to the bluetooth program to get the stack/error, but they were of no use.

I will pick this back up soon but I have been very swamped with work/other projects atm.

**Comment by jlennox** [comment]
Apologies for the late response. I never did manage to get my bluetooth dongle working so I made a better mock data source so I could still test the program. I found a deadlock that sounds like your issue. Mind testing again?

[heartrate-1.4-beta5.zip](https://github.com/jlennox/HeartRate/files/2974179/heartrate-1.4-beta5.zip)

**Comment by jlennox** [comment]
I have also updated it so you can change the colors/fonts by right clicking on the system tray icon. This way you can use the common color selection dialog to select the color instead of messing with hex codes.

[heartrate-1.4-beta6.zip](https://github.com/jlennox/HeartRate/files/2974191/heartrate-1.4-beta6.zip)

**Comment by jlennox** [comment]
I'm closing this for now because of lack of feedback. Please open a new case if you still have issues!
